service: Devices_API

provider:
  name: aws
  runtime: python3.6
  memorySize: 128
  timeout: 10
  versionFunctions: false
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}
  stackName: devicesAPI
  apiName: PythonAWS-API-Gateway
  endpointType: REGIONAL
  role: 'arn:aws:iam::xxcxc:role/LambdaIOTRole'
 

functions:
  registration:
    handler: handler.handler
    events:
      - http:
          path: /device_registration
          method: get
          description: "device registration api"

package:
  exclude:
    - .eslintrc.yml
    - .gitignore
    - .git/**
    - .vscode/**
    - test/**
    - coverage/**
    - README.md
    - local.py
    - testing.py
    - test-devices.py

custom:
  wsgi:
    app: handler.app
    packRequirements: false

plugins:
  - serverless-wsgi
  - serverless-python-requirements
