service: security_automation

provider:
  name: aws
  runtime: python3.6
  memorySize: 128
  timeout: 10
  versionFunctions: false
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}
  stackName: security-automation-stack
  apiName: PythonAWS-API-Gateway
  endpointType: REGIONAL

functions:
  securityautomation:
    handler: handler.handler
    events:
      - http:
          path: /
          method: get
          description: "default api"
      - http:
          path: /v1/security
          method: get
          description: "security api"
package:
  exclude:
    - .eslintrc.yml
    - .gitignore
    - .git/**
    - .vscode/**
    - test/**
    - coverage/**
    - README.md
    - local.py

custom:
  wsgi:
    app: handler.app
    packRequirements: false

plugins:
  - serverless-wsgi
  - serverless-python-requirements
